spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/gerenciador_salas_test
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

logging:
  level:
    br.com.senac.gerenciadordesalas: INFO